import {expect, test} from '@playwright/test'

test('旧版单次按钮执行、停止、等待任务和自然完成', async ({page}, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route('https://**', route => route.abort())
  await page.goto('/')
  const pending = page.locator('#pywebio-scope-pending_tasks')
  const running = page.locator('#pywebio-scope-running_tasks')
  const waiting = page.locator('#pywebio-scope-waiting_tasks')
  const research = pending.locator('#pywebio-scope-overview-task_Research')
  const commission = pending.locator('#pywebio-scope-overview-task_Commission')
  const exercise = waiting.locator('#pywebio-scope-overview-task_Exercise')
  await expect(research.getByRole('button', {name: '执行一次'})).toBeEnabled()
  await expect(exercise.getByRole('button', {name: '执行一次'})).toBeEnabled()
  await page.waitForFunction(() => {
    const scopes = [...document.querySelectorAll('[id^="pywebio-scope-"]')]
    const jquery = Reflect.get(window, 'jQuery')
    return scopes.length > 0 && scopes.every(scope => getComputedStyle(scope).opacity === '1')
      && (!jquery || jquery.timers.length === 0)
  })
  await page.screenshot({path: testInfo.outputPath('legacy-run-once-idle.png'), fullPage: true})
  await research.getByRole('button', {name: '执行一次'}).click()
  await expect(running.locator('#pywebio-scope-overview-task_Research').getByRole('button', {name: '停止'})).toBeEnabled()
  await expect(commission.getByRole('button', {name: '执行一次'})).toBeDisabled()
  await expect(exercise.getByRole('button', {name: '执行一次'})).toBeDisabled()
  await expect(commission.getByRole('button', {name: '设置'})).toBeEnabled()
  await expect(page.locator('#pywebio-scope-scheduler_btn').getByRole('button', {name: '单次任务运行中'})).toBeDisabled()
  await page.waitForFunction(() => {
    const scopes = [...document.querySelectorAll('[id^="pywebio-scope-"]')]
    const jquery = Reflect.get(window, 'jQuery')
    return scopes.length > 0 && scopes.every(scope => getComputedStyle(scope).opacity === '1')
      && (!jquery || jquery.timers.length === 0)
  })
  await page.screenshot({path: testInfo.outputPath('legacy-run-once-running.png'), fullPage: true})
  await running.getByRole('button', {name: '停止'}).click()
  await expect(research.getByRole('button', {name: '执行一次'})).toBeEnabled()
  await expect(running).toContainText('无任务')
  await exercise.getByRole('button', {name: '执行一次'}).click()
  await expect(running.locator('#pywebio-scope-overview-task_Exercise').getByRole('button', {name: '停止'})).toBeEnabled()
  await page.getByRole('button', {name: '模拟自然完成'}).click()
  await expect(exercise.getByRole('button', {name: '执行一次'})).toBeEnabled()
  await expect(page.locator('#pywebio-scope-scheduler_btn').getByRole('button', {name: '启动'})).toBeEnabled()
  await page.locator('#pywebio-scope-scheduler_btn').getByRole('button', {name: '启动'}).click()
  await expect(running.locator('#pywebio-scope-overview-task_Commission')).toContainText('委托')
  await expect(research.getByRole('button', {name: '执行一次'})).toBeDisabled()
  await page.locator('#pywebio-scope-scheduler_btn').getByRole('button', {name: '停止'}).click()
  await expect(commission.getByRole('button', {name: '执行一次'})).toBeEnabled()
  expect(errors).toEqual([])
})
